# Welcome to Nubia Jekyll Theme!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

theme_version: 1.0.5

# Site settings
title:              Musings on the human condition
logo:               # Logo image URL
description:        Thoughts, Stories and Ideas
baseurl:            '' # The subpath of your site, e.g. /blog
url:                'http://valy.space/' # The base hostname & protocol for your site
twitter:            https://twitter.com/valyermakova
linkedin:          https://www.linkedin.com/valeria-yermakova

markdown:  kramdown
permalink: pretty
paginate:  11
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  ahmad:
    name:     Val Yermakova
    bio:      Co-founder of Warmly; xGoogle security analyst; Fulbright in China; lover of handstands. 
    gravatar: https://https://secure.gravatar.com/avatar/fa9a1e686aef144d2cb6a95115a2355f
    email:    v.yerminator+blog@gmail.com
    website:  http://valy.space
    github:   https://github.com/yermakova
    twitter:  https://twitter.com/valyermakova